#!/usr/bin/env bash
# Generate the Homebrew formula for a released version and (optionally) push it
# to the tap. This is outward-facing: it mutates an external repository, so the
# push step requires an explicit confirmation unless HATS_TAP_CONFIRM=1.
#
# Usage:
#   scripts/update-tap.sh <version>        # generate Formula/hats.rb, then prompt to push
#   HATS_TAP_CONFIRM=1 scripts/update-tap.sh <version>   # non-interactive push (CI)
#
# Requires: a published GitHub release v<version> with the .sha256 sidecar files
# for the four Unix archives. When GH_TOKEN is set (the release workflow passes a
# GitHub App installation token) it is used to clone and push the tap; otherwise
# the local git credential helper is used.
set -euo pipefail

VERSION="${1:?usage: update-tap.sh <version> (without leading v)}"
VERSION="${VERSION#v}"
REPO="planesailingio/hats"
TAP_REPO="planesailingio/homebrew-tools"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

# (os, arch) -> Rust target. A function rather than an associative array so this
# also runs under the bash 3.2 that macOS ships, for local dry runs.
target_for() {
  case "$1" in
    darwin_amd64) echo "x86_64-apple-darwin" ;;
    darwin_arm64) echo "aarch64-apple-darwin" ;;
    linux_amd64)  echo "x86_64-unknown-linux-gnu" ;;
    linux_arm64)  echo "aarch64-unknown-linux-gnu" ;;
    *) echo "update-tap: unknown build '$1'" >&2; return 1 ;;
  esac
}

fetch_sha() {
  local build="$1"
  local target file sha
  target="$(target_for "$build")"
  file="hats_${VERSION}_${target}.tar.gz.sha256"
  sha="$(curl -fsSL "${BASE}/${file}" | tr -d '[:space:]')"
  if ! [[ "$sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "update-tap: ${file} does not contain a SHA-256 hex digest: '${sha}'" >&2
    exit 1
  fi
  echo "$sha"
}

SHA_DARWIN_AMD64="$(fetch_sha darwin_amd64)"
SHA_DARWIN_ARM64="$(fetch_sha darwin_arm64)"
SHA_LINUX_AMD64="$(fetch_sha linux_amd64)"
SHA_LINUX_ARM64="$(fetch_sha linux_arm64)"

url() { echo "${BASE}/hats_${VERSION}_$(target_for "$1").tar.gz"; }

OUT="Formula/hats.rb"
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<RUBY
# typed: false
# frozen_string_literal: true

# This file is generated by scripts/update-tap.sh in planesailingio/hats. DO NOT EDIT.
class Hats < Formula
  desc "One laptop, many hats: dotfiles and per-shell client profiles"
  homepage "https://github.com/planesailingio/hats"
  version "${VERSION}"
  license "MIT"

  # The age plugin that unseals the credential envelope. hats drives it as a
  # subprocess, and the age crate resolves it on PATH at call time, so it has to
  # be present rather than merely suggested.
  #
  # On Linux it also needs a running pcscd to reach the smartcard; that is a
  # system service Homebrew does not manage, and \`hats doctor\` says so.
  depends_on "age-plugin-yubikey"

  # git is the only other hard requirement, and every machine with a dotfiles
  # repo already has it. fzf and kubectl are optional and reported by
  # \`hats doctor\`.

  on_macos do
    on_intel do
      url "$(url darwin_amd64)"
      sha256 "${SHA_DARWIN_AMD64}"
    end
    on_arm do
      url "$(url darwin_arm64)"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "$(url linux_amd64)"
        sha256 "${SHA_LINUX_AMD64}"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "$(url linux_arm64)"
        sha256 "${SHA_LINUX_ARM64}"
      end
    end
  end

  def install
    bin.install "bin/hats"
    bash_completion.install "completions/hats.bash" => "hats"
    zsh_completion.install "completions/_hats"
    fish_completion.install "completions/hats.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hats --version")
    # doctor exits non-zero in the sandbox because no repo is cloned there, but
    # the report must still name the git check, which proves it ran.
    assert_match "git", shell_output("#{bin}/hats doctor 2>&1 || true")
  end
end
RUBY

echo "Generated ${OUT} for v${VERSION}."

if [ "${HATS_TAP_CONFIRM:-0}" != "1" ]; then
  printf 'Push %s to %s? This updates a public repository. [y/N] ' "$OUT" "$TAP_REPO"
  read -r reply
  case "$reply" in
    y|Y) ;;
    *) echo "Not pushing. The formula is at ./${OUT}."; exit 0 ;;
  esac
fi

if [ -n "${GH_TOKEN:-}" ]; then
  CLONE_URL="https://x-access-token:${GH_TOKEN}@github.com/${TAP_REPO}.git"
else
  CLONE_URL="https://github.com/${TAP_REPO}.git"
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
git clone --quiet --depth 1 "$CLONE_URL" "$WORK"
mkdir -p "$WORK/Formula"
cp "$OUT" "$WORK/Formula/hats.rb"
git -C "$WORK" add Formula/hats.rb
if git -C "$WORK" diff --cached --quiet; then
  echo "Tap already has hats ${VERSION}; nothing to push."
  exit 0
fi
git -C "$WORK" \
  -c user.name="hats release bot" \
  -c user.email="release@planesailing.io" \
  commit --quiet -m "hats ${VERSION}"
git -C "$WORK" push --quiet
echo "Pushed hats ${VERSION} to ${TAP_REPO}."
