#? btop config — managed by chezmoi
color_theme = "catppuccin_mocha"
theme_background = False
truecolor = True
vim_keys = True
rounded_corners = True
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
